---
- hosts: localhost
  vars: 
    - php_versions: []
  roles:
    - roles/homebrew
    - roles/zsh
    - roles/coreutils
    - roles/git
    - roles/curl
    - roles/jenv
    - roles/supervisord
    - roles/efk
    - roles/logrotate
    - roles/fakesendmail
    - roles/dnsmasq
    - roles/percona-server-56
    - roles/percona-server-57
    - roles/mongodb
    - roles/redis
    - roles/php-56
    - roles/php-70
    - roles/php-71
    - roles/php-72
    - roles/nginx
    - roles/nginx-php-fpm
    - roles/nodejs
    - roles/xhgui
    - roles/compass
    - roles/less
    - roles/php-tools
  post_tasks:
    - name: "Stopping supervisord"
      shell: "launchctl unload /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist"
      become: true
      tags:
        - always
    
    - name: "Starting supervisord"
      shell: "launchctl load /Library/LaunchDaemons/homebrew.mxcl.supervisor.plist"
      become: true
      tags:
        - always
