---
- hosts: localhost
  vars:
  - php_versions: []
  pre_tasks:
  - name: "Register brew_user fact"
    set_fact:
      brew_user: "{{ mac_user|default(ansible_env.USER) }}"
    tags:
    - always

  - name: "Resolve user group"
    shell: "id -gn"
    register: result
    tags:
    - always

  - name: "Register brew_group fact"
    set_fact: brew_group="{{ result.stdout }}"
    tags:
    - always

  - name: "Resolve home dir"
    shell: "eval echo ~$USER"
    register: result
    tags:
    - always

  - name: "Register brew_user_home_dir fact"
    set_fact: brew_user_home_dir="{{ result.stdout }}"
    tags:
    - always
  - include_tasks: "{{ ansible_system | lower }}_pre.yml"
    tags:
    - always
  roles:
  - name: homebrew
    include_role:
      name: homebrew
    when: "ansible_system == 'Darwin'"

  - name: linuxbrew
    include_role:
      name: linuxbrew
    when: "ansible_system == 'Linux'"
  - zsh
  - coreutils
  - role: flock
    when: "ansible_system == 'Darwin'"
  - git
  - curl
  - jenv
  - golang
  - supervisord
  - logrotate
  - nginx
  - efk
  - efk+nginx
  - fakesendmail
  - dnsmasq
  - percona-server-56
  - percona-server-57
  - role: mongodb
    when: ansible_system == "Darwin"
  - redis
  - php-56
  - php-70
  - php-71
  - php-72
  - nginx-php-fpm
  - nodejs
  - php-tools
  - xhgui
  - compass
  - less
  post_tasks:
  - include_tasks: "{{ ansible_system | lower }}_post.yml"
    tags:
    - always
  - name: "Unlinking python@2"
    homebrew:
      name: "python@2"
      state: unlinked
    tags:
    - always
