---
- hosts: localhost
  # strategy: debug
  environment:
    PATH: "{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:{{ ansible_env.PATH}}"
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
  vars:
    - php_versions: []
    - systemd_service_disabled: []
    - systemd_service_restarted: []
    - systemd_service_started: []
    - service_disabled: []
    - service_restarted: []
    - service_started: []
    - brew_brew_bin_path: "{{ brew_install_path }}/bin"
  pre_tasks:
    - name: "Register brew_user fact"
      set_fact:
        brew_user: "{{ mac_user|default(ansible_env.USER) }}"
      tags:
        - always

    - name: "Resolve user group"
      shell: "id -gn"
      register: result
      tags:
        - always

    - name: "Register brew_group fact"
      set_fact: brew_group="{{ result.stdout }}"
      tags:
        - always

    - name: "Resolve home dir"
      shell: "eval echo ~$USER"
      register: result
      tags:
        - always

    - name: "Register brew_user_home_dir fact"
      set_fact: brew_user_home_dir="{{ result.stdout }}"
      tags:
        - always

    - include_tasks: "{{ ansible_system | lower }}_pre.yml"
      tags:
        - always

    - name: "Adding brew bin to PATH (root/linux)"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      become: yes
      with_items:
        - /root/.bashrc
        - /root/.zshrc
      when: "ansible_system == 'Linux'"
      tags:
        - always

    - name: "Adding brew bin to PATH (root/macos)"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      become: yes
      with_items:
        - /var/root/.bashrc
        - /var/root/.zshrc
      when: "ansible_system == 'Darwin'"
      tags:
        - always

    - name: "Adding brew bin to PATH ({{ brew_user }})"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      with_items:
        - "{{ brew_user_home_dir }}/.bashrc"
        - "{{ brew_user_home_dir }}/.zshrc"
      tags:
        - always

  roles:
    - name: yedit
    - name: homebrew
      include_role:
        name: homebrew
      when: "ansible_system == 'Darwin'"
    - name: linuxbrew
      include_role:
        name: linuxbrew
      when: "ansible_system == 'Linux'"
      tags:
        - always
    - role: openssl
      tags:
        - always
    - role: python3
      tags:
        - always
    - role: zsh
      tags:
        - always
    - role: vim
      tags:
        - always
    - role: coreutils
      tags:
        - always
    - role: flock
      when: "ansible_system == 'Darwin'"
      tags:
        - always
    - role: git
      tags:
        - always
    - jenv
    - role: golang
      tags:
        - always
#    - role: torrent-cli
#      tags:
#        - always
    - role: supervisord
      tags:
        - always
    - logrotate
    - nginx
    - role: efk
      tags:
        - efk
    - role: efk+nginx
      tags:
        - efk
    - fakesendmail
    - role: dnsmasq
      tags:
        - dnsmasq
    - role: mysql-57
      tags:
        - mysql57
    - role: mysql-80
      tags:
        - mysql80
    - role: ruby
      tags:
        - always
    - redis
    - php-56
    - php-70
    - php-71
    - php-72
    - php-73
    - php-74
    - php-80
    - php-81
    - php-82
    - php-83
    - nginx-php-fpm
    - role: nodejs
      tags:
        - always
    - role: php-tools
      tags:
        - always
  post_tasks:
    - name: "Adding brew bin to PATH for root user (Linux)"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      become: yes
      with_items:
        - /root/.bashrc
        - /root/.zshrc
      when: "ansible_system == 'Linux'"
      tags:
        - always

    - name: "Adding brew bin to PATH for root user (Darwin)"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      become: yes
      with_items:
        - /var/root/.bashrc
        - /var/root/.zshrc
      when: "ansible_system == 'Darwin'"
      tags:
        - always

    - name: "Adding brew bin to PATH"
      blockinfile:
        dest: '{{ item }}'
        marker: "# {mark} brew PATH"
        block: |
          export PATH="{{ brew_install_path }}/bin:{{ brew_install_path }}/sbin:$PATH"
        create: yes
        mode: 0644
        insertbefore: BOF
      with_items:
        - "{{ brew_user_home_dir }}/.bashrc"
        - "{{ brew_user_home_dir }}/.zshrc"
      tags:
        - always
    - include_tasks: "{{ ansible_system | lower }}_post.yml"
      tags:
        - always
#    - name: "Linking python@2"
#      shell: "brew link --overwrite python@2"
#      tags:
#      - always
